apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: cicd-token
  namespace: app-team1

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: app-team1
spec: {}
status: {}
