apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    id: vol-1
  name: pv-volume
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /tmp/k8s-vol


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    id: vol-1
  name: pvc-volume
spec:
  resources:
    requests:
      storage: 40Mi

  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  selector:
    matchLabels:
      id: vol-1

  

  
