apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cka-exam
spec: {}
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: cka-exam
  labels:
    run: cka-pod
  name: cka-pod
spec:
  containers:
  - image: nginx
    name: cka-pod
    resources: 
      limits:
        memory: 20Mi
        cpu: 500m

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
