apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-backend
  name: app-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-backend
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-playground-worker2
          - weight: 2 
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-playground-worker 
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
