apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-affinity
  name: pod-with-affinity
  namespace: cka
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          matchExpressions:
          -  key: kubernetes.io/hostname
             operator: In
             values:
             - k8s-playground-worker2
  containers:
  - image: nginx
    name: pod-with-affinity
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
