apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: big-corp-app
  name: big-corp-app
spec:
  containers:
  - image: busybox
    name: sidecar
    command: 
    - /bin/sh
    - -c 
    - touch /var/log/bigp-app.log && while true; do  tail -n+1 -f /var/log/bigp-app.log   ; done
    volumeMounts:
    - name: log
      mountPath: /var/log
  - image: nginx
    name: big-corp-app
    command:
    - /bin/sh 
    - -c 
    - counter=0; while true; do echo ${counter} >> /var/log/bigp-app.log; counter=$((counter + 1)); done;
    volumeMounts:
    - name: log
      mountPath: /var/log
  dnsPolicy: ClusterFirst
  volumes: 
  - name: log
    emptyDir: {}
  restartPolicy: Always
status: {}
