apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multicontainer-playground
  name: multicontainer-playground
spec:
  volumes:
  - name: shared-vol
    emptyDir: {}
  containers:
  - image: nginx:1.17.6-alpine
    name: c1
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

    volumeMounts:
    - name: shared-vol
      mountPath: /data

    resources: {}
  - image: busybox:1.31.1
    name: c2
    command: 
    - /bin/sh
    - -c
    - while true; do date >> /data/date.log; sleep 1; done 
    volumeMounts:
    - name: shared-vol
      mountPath: /data
    resources: {}
  - image: busybox:1.31.1
    name: c3
    command:
    - /bin/sh
    - -c
    - tail -f /data/date.log
    volumeMounts:
    - name: shared-vol
      mountPath: /data
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
