apiVersion: batch/v1
kind: Job
metadata:
  name: a-job
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: nginx
        name: a-job
        command: 
        - /bin/sh
        - -c 
        # - abcdczsd
        # exit code 1 
        - sleep 1; exit 1;
        resources: {}
      restartPolicy: Never
status: {}
