apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-port-from-namespace
  namespace: myapp
spec:
  policyTypes:
  - Ingress
  ingress: 
  - from: 
    - namespaceSelector:
        matchLabels:
          project: myapp
    ports:
    - protocol: TCP
      port: 9000
