apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: front-end
  name: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front-end
    spec:
      containers:
      - image: nginx
        name: nginx
        ports: 
        - protocol: TCP
          containerPort: 80
          name: http
        resources: {}
status: {}

## expose service kubectl  expose deployment front-end --name=front-end-svc --port=80 --protocol=TCP --type=NodePort
