apiVersion: v1
data:
  val-litteral: value
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: vars

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
data:
  nginx.conf: |
    server {
        listen 80;
         
         location = /status {
             access_log off;
             default_type text/plain;
             add_header Content-Type text/plain;
             return 200 "alive";
        }
        
         location / {
            gzip off;
            root /usr/share/nginx/html/;
            index  index.html;
        }
        
        location ~* \.(js|jpg|png|css)$ {
            root /usr/share/nginx/html/;
        }
    } 