apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static-pod
  name: static-pod
spec:
  containers:
  - image: nginx
    name: static-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

## ps -aux to get kubelet process , then get the config.yaml file location , then you can get the location when you can create the static pod ( ex /etc/kubernetes/manifests)