apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safari-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  volumeName: safari-pv