apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-pod
  name: time-pod
spec:
  containers:
  - image: busybox
    name: time-pod
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
    command:
    - /bin/sh 
    - -c
    - sleep 3200
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
