apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
spec:
  volumes:
  - name: pod-secret
    secret: 
      secretName: secret-for-pod
  containers:
  - image: busybox:1.31.1
    name: secret-pod
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          name: secrets
          key: user
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          name: secrets
          key: pass
    volumeMounts:
    - name: pod-secret
      mountPath: /tmp/secret1
      readOnly: true
    command:
    - /bin/sh 
    - -c 
    - sleep 3600
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
