apiVersion: v1
data:
  DB_SECRET: czNjcjN0
kind: Secret
metadata:
  creationTimestamp: null
  name: secret-for-pod

---
apiVersion: v1
data:
  pass: MTIzNA==
  user: dXNlcjE=
kind: Secret
metadata:
  creationTimestamp: null
  name: secrets
